:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\OpenApi
dotnet build src\OpenApi
echo Now, run the following to start the project: dotnet run -p src\OpenApi\OpenApi.csproj --launch-profile web.
echo.
