/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using OpenApi.Attributes;
using OpenApi.Models;

namespace OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class CompleteOrderApiController : ControllerBase
    { 
        /// <summary>
        /// Завершить заказ
        /// </summary>
        /// <remarks>Позволяет завершить заказ</remarks>
        /// <param name="courierId">Идентификатор курьера</param>
        /// <param name="orderId">Идентификатор заказа</param>
        /// <response code="200">Успешный ответ</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="409">Конфликт при завершении заказа</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpPost]
        [Route("/api/v1/couriers/{courierId}/orders/{orderId}/complete")]
        [ValidateModelState]
        [SwaggerOperation("CompleteOrder")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Конфликт при завершении заказа")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public abstract Task<IActionResult> CompleteOrder([FromRoute (Name = "courierId")][Required]Guid courierId, [FromRoute (Name = "orderId")][Required]Guid orderId);
    }
}
