/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using OpenApi.Attributes;
using OpenApi.Models;

namespace OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class CreateCourierApiController : ControllerBase
    { 
        /// <summary>
        /// Добавить курьера
        /// </summary>
        /// <remarks>Позволяет добавить курьера</remarks>
        /// <param name="newCourier">Курьер</param>
        /// <response code="201">Курьер успешно создан</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="409">Конфликт при создании курьера</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpPost]
        [Route("/api/v1/couriers")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateCourier")]
        [SwaggerResponse(statusCode: 201, type: typeof(CreateCourierResponse), description: "Курьер успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Конфликт при создании курьера")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public abstract Task<IActionResult> CreateCourier([FromBody]NewCourier newCourier);
    }
}
