/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using OpenApi.Attributes;
using OpenApi.Models;

namespace OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class CreateOrderApiController : ControllerBase
    { 
        /// <summary>
        /// Создать заказ
        /// </summary>
        /// <remarks>Позволяет создать заказ с целью тестирования</remarks>
        /// <param name="newOrder">Новый заказ</param>
        /// <response code="201">Заказ успешно создан</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="409">Конфликт при создании заказа</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpPost]
        [Route("/api/v1/orders")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateOrder")]
        [SwaggerResponse(statusCode: 201, type: typeof(CreateOrderResponse), description: "Заказ успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Конфликт при создании заказа")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public abstract Task<IActionResult> CreateOrder([FromBody]NewOrder newOrder);
    }
}
