/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using OpenApi.Attributes;
using OpenApi.Models;

namespace OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class GetCouriersApiController : ControllerBase
    { 
        /// <summary>
        /// Получить всех курьеров
        /// </summary>
        /// <remarks>Позволяет получить всех курьеров</remarks>
        /// <response code="200">Успешный ответ</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpGet]
        [Route("/api/v1/couriers")]
        [ValidateModelState]
        [SwaggerOperation("GetCouriers")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Courier>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public abstract Task<IActionResult> GetCouriers();
    }
}
