/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using OpenApi.Attributes;
using OpenApi.Models;

namespace OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class MoveCourierApiController : ControllerBase
    { 
        /// <summary>
        /// Переместить курьера
        /// </summary>
        /// <remarks>Позволяет переместить курьера</remarks>
        /// <param name="courierId">Идентификатор курьера</param>
        /// <param name="location">Местоположение</param>
        /// <response code="200">Успешный ответ</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="409">Конфликт при перемещении курьера</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpPost]
        [Route("/api/v1/couriers/{courierId}/move")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("MoveCourier")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Конфликт при перемещении курьера")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public abstract Task<IActionResult> MoveCourier([FromRoute (Name = "courierId")][Required]Guid courierId, [FromBody]Location location);
    }
}
